/**
 * Supabase Database Types for FORGE
 *
 * This file will be auto-generated by running:
 * supabase gen types typescript --project-id YOUR_PROJECT_REF > types/supabase.ts
 *
 * For now, this contains the initial schema types matching our migration files.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      workspace_members: {
        Row: {
          id: string;
          workspace_id: string;
          user_id: string;
          role: "owner" | "admin" | "member" | "viewer";
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          user_id: string;
          role: "owner" | "admin" | "member" | "viewer";
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          user_id?: string;
          role?: "owner" | "admin" | "member" | "viewer";
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "workspace_members_workspace_id_fkey";
            columns: ["workspace_id"];
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "workspace_members_user_id_fkey";
            columns: ["user_id"];
            referencedRelation: "users";
            referencedColumns: ["id"];
          }
        ];
      };
      workspaces: {
        Row: {
          id: string;
          name: string;
          slug: string;
          team_size: string | null;
          plan: "free" | "pro" | "team" | "enterprise";
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug?: string;
          team_size?: string | null;
          plan?: "free" | "pro" | "team" | "enterprise";
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          team_size?: string | null;
          plan?: "free" | "pro" | "team" | "enterprise";
          created_by?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      users: {
        Row: {
          id: string;
          workspace_id: string | null;
          email: string;
          full_name: string | null;
          display_name: string | null;
          role: string | null;
          avatar_url: string | null;
          onboarding_completed: boolean;
          created_at: string;
          updated_at: string | null;
        };
        Insert: {
          id: string;
          workspace_id?: string | null;
          email: string;
          full_name?: string | null;
          display_name?: string | null;
          role?: string | null;
          avatar_url?: string | null;
          onboarding_completed?: boolean;
          created_at?: string;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          workspace_id?: string | null;
          email?: string;
          full_name?: string | null;
          display_name?: string | null;
          role?: string | null;
          avatar_url?: string | null;
          onboarding_completed?: boolean;
          created_at?: string;
          updated_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "users_workspace_id_fkey";
            columns: ["workspace_id"];
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          }
        ];
      };
      jira_connections: {
        Row: {
          id: string;
          workspace_id: string;
          site_url: string;
          access_token: string;
          refresh_token: string | null;
          token_expires: string | null;
          last_synced_at: string | null;
          sync_status: "idle" | "syncing" | "error";
        };
        Insert: {
          id?: string;
          workspace_id: string;
          site_url: string;
          access_token: string;
          refresh_token?: string | null;
          token_expires?: string | null;
          last_synced_at?: string | null;
          sync_status?: "idle" | "syncing" | "error";
        };
        Update: {
          id?: string;
          workspace_id?: string;
          site_url?: string;
          access_token?: string;
          refresh_token?: string | null;
          token_expires?: string | null;
          last_synced_at?: string | null;
          sync_status?: "idle" | "syncing" | "error";
        };
        Relationships: [
          {
            foreignKeyName: "jira_connections_workspace_id_fkey";
            columns: ["workspace_id"];
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          }
        ];
      };
      stories: {
        Row: {
          id: string;
          workspace_id: string;
          jira_id: string;
          jira_key: string;
          title: string;
          description: string | null;
          acceptance_criteria: string | null;
          story_points: number | null;
          status: string | null;
          assignee_id: string | null;
          epic_key: string | null;
          sprint_id: string | null;
          labels: string[] | null;
          jira_updated_at: string | null;
          synced_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          jira_id: string;
          jira_key: string;
          title: string;
          description?: string | null;
          acceptance_criteria?: string | null;
          story_points?: number | null;
          status?: string | null;
          assignee_id?: string | null;
          epic_key?: string | null;
          sprint_id?: string | null;
          labels?: string[] | null;
          jira_updated_at?: string | null;
          synced_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          jira_id?: string;
          jira_key?: string;
          title?: string;
          description?: string | null;
          acceptance_criteria?: string | null;
          story_points?: number | null;
          status?: string | null;
          assignee_id?: string | null;
          epic_key?: string | null;
          sprint_id?: string | null;
          labels?: string[] | null;
          jira_updated_at?: string | null;
          synced_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "stories_workspace_id_fkey";
            columns: ["workspace_id"];
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          }
        ];
      };
      rubrics: {
        Row: {
          id: string;
          workspace_id: string;
          name: string;
          is_default: boolean;
          weights: Json;
          blocklist: string[] | null;
          threshold: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          name: string;
          is_default?: boolean;
          weights: Json;
          blocklist?: string[] | null;
          threshold?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          name?: string;
          is_default?: boolean;
          weights?: Json;
          blocklist?: string[] | null;
          threshold?: number;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "rubrics_workspace_id_fkey";
            columns: ["workspace_id"];
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          }
        ];
      };
      story_scores: {
        Row: {
          id: string;
          story_id: string;
          rubric_id: string;
          total_score: number;
          completeness: number | null;
          clarity: number | null;
          estimability: number | null;
          traceability: number | null;
          testability: number | null;
          ai_suggestions: Json | null;
          scored_at: string;
        };
        Insert: {
          id?: string;
          story_id: string;
          rubric_id: string;
          total_score: number;
          completeness?: number | null;
          clarity?: number | null;
          estimability?: number | null;
          traceability?: number | null;
          testability?: number | null;
          ai_suggestions?: Json | null;
          scored_at?: string;
        };
        Update: {
          id?: string;
          story_id?: string;
          rubric_id?: string;
          total_score?: number;
          completeness?: number | null;
          clarity?: number | null;
          estimability?: number | null;
          traceability?: number | null;
          testability?: number | null;
          ai_suggestions?: Json | null;
          scored_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "story_scores_story_id_fkey";
            columns: ["story_id"];
            referencedRelation: "stories";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "story_scores_rubric_id_fkey";
            columns: ["rubric_id"];
            referencedRelation: "rubrics";
            referencedColumns: ["id"];
          }
        ];
      };
      signal_updates: {
        Row: {
          id: string;
          workspace_id: string;
          author_id: string;
          title: string | null;
          sprint_ref: string | null;
          context_data: Json | null;
          audiences: string[] | null;
          drafts: Json | null;
          status: "draft" | "sent" | "archived";
          sent_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          author_id: string;
          title?: string | null;
          sprint_ref?: string | null;
          context_data?: Json | null;
          audiences?: string[] | null;
          drafts?: Json | null;
          status?: "draft" | "sent" | "archived";
          sent_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          author_id?: string;
          title?: string | null;
          sprint_ref?: string | null;
          context_data?: Json | null;
          audiences?: string[] | null;
          drafts?: Json | null;
          status?: "draft" | "sent" | "archived";
          sent_at?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "signal_updates_workspace_id_fkey";
            columns: ["workspace_id"];
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "signal_updates_author_id_fkey";
            columns: ["author_id"];
            referencedRelation: "users";
            referencedColumns: ["id"];
          }
        ];
      };
      decisions: {
        Row: {
          id: string;
          workspace_id: string;
          created_by: string;
          title: string;
          description: string | null;
          decision_type: "scope_change" | "priority_shift" | "resource_allocation" | "technical_decision" | "process_change" | "risk_acceptance" | "other";
          context: Json;
          decision: Json;
          ai_summary: string | null;
          ai_risk_assessment: Json | null;
          outcome_status: "pending" | "successful" | "partial" | "failed" | "unknown";
          outcome: Json | null;
          outcome_evaluated_at: string | null;
          outcome_evaluated_by: string | null;
          tags: string[];
          visibility: "private" | "team" | "workspace";
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          created_by: string;
          title: string;
          description?: string | null;
          decision_type: "scope_change" | "priority_shift" | "resource_allocation" | "technical_decision" | "process_change" | "risk_acceptance" | "other";
          context?: Json;
          decision: Json;
          ai_summary?: string | null;
          ai_risk_assessment?: Json | null;
          outcome_status?: "pending" | "successful" | "partial" | "failed" | "unknown";
          outcome?: Json | null;
          outcome_evaluated_at?: string | null;
          outcome_evaluated_by?: string | null;
          tags?: string[];
          visibility?: "private" | "team" | "workspace";
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          created_by?: string;
          title?: string;
          description?: string | null;
          decision_type?: "scope_change" | "priority_shift" | "resource_allocation" | "technical_decision" | "process_change" | "risk_acceptance" | "other";
          context?: Json;
          decision?: Json;
          ai_summary?: string | null;
          ai_risk_assessment?: Json | null;
          outcome_status?: "pending" | "successful" | "partial" | "failed" | "unknown";
          outcome?: Json | null;
          outcome_evaluated_at?: string | null;
          outcome_evaluated_by?: string | null;
          tags?: string[];
          visibility?: "private" | "team" | "workspace";
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "decisions_workspace_id_fkey";
            columns: ["workspace_id"];
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "decisions_created_by_fkey";
            columns: ["created_by"];
            referencedRelation: "users";
            referencedColumns: ["id"];
          }
        ];
      };
      decision_story_links: {
        Row: {
          id: string;
          decision_id: string;
          story_id: string;
          link_type: "caused_by" | "affects" | "blocks" | "related";
          created_at: string;
        };
        Insert: {
          id?: string;
          decision_id: string;
          story_id: string;
          link_type: "caused_by" | "affects" | "blocks" | "related";
          created_at?: string;
        };
        Update: {
          id?: string;
          decision_id?: string;
          story_id?: string;
          link_type?: "caused_by" | "affects" | "blocks" | "related";
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "decision_story_links_decision_id_fkey";
            columns: ["decision_id"];
            referencedRelation: "decisions";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "decision_story_links_story_id_fkey";
            columns: ["story_id"];
            referencedRelation: "stories";
            referencedColumns: ["id"];
          }
        ];
      };
      decision_templates: {
        Row: {
          id: string;
          workspace_id: string;
          name: string;
          decision_type: string;
          template: Json;
          usage_count: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          name: string;
          decision_type: string;
          template: Json;
          usage_count?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          name?: string;
          decision_type?: string;
          template?: Json;
          usage_count?: number;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "decision_templates_workspace_id_fkey";
            columns: ["workspace_id"];
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          }
        ];
      };
      jira_sync_operations: {
        Row: {
          id: string;
          workspace_id: string;
          story_id: string | null;
          jira_issue_key: string;
          operation_type: "update_field" | "add_comment" | "transition" | "apply_suggestion" | "add_label" | "remove_label";
          payload: Json;
          status: "pending" | "in_progress" | "completed" | "failed" | "conflict";
          error_message: string | null;
          retry_count: number;
          max_retries: number;
          initiated_by: string | null;
          completed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          story_id?: string | null;
          jira_issue_key: string;
          operation_type: "update_field" | "add_comment" | "transition" | "apply_suggestion" | "add_label" | "remove_label";
          payload: Json;
          status?: "pending" | "in_progress" | "completed" | "failed" | "conflict";
          error_message?: string | null;
          retry_count?: number;
          max_retries?: number;
          initiated_by?: string | null;
          completed_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          story_id?: string | null;
          jira_issue_key?: string;
          operation_type?: "update_field" | "add_comment" | "transition" | "apply_suggestion" | "add_label" | "remove_label";
          payload?: Json;
          status?: "pending" | "in_progress" | "completed" | "failed" | "conflict";
          error_message?: string | null;
          retry_count?: number;
          max_retries?: number;
          initiated_by?: string | null;
          completed_at?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "jira_sync_operations_workspace_id_fkey";
            columns: ["workspace_id"];
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          }
        ];
      };
      notification_events: {
        Row: {
          id: string;
          workspace_id: string;
          event_type: string;
          event_data: Json;
          source_type: string;
          source_id: string | null;
          importance: "low" | "normal" | "high" | "critical";
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          event_type: string;
          event_data: Json;
          source_type: string;
          source_id?: string | null;
          importance?: "low" | "normal" | "high" | "critical";
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          event_type?: string;
          event_data?: Json;
          source_type?: string;
          source_id?: string | null;
          importance?: "low" | "normal" | "high" | "critical";
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "notification_events_workspace_id_fkey";
            columns: ["workspace_id"];
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          }
        ];
      };
      notifications: {
        Row: {
          id: string;
          workspace_id: string;
          user_id: string;
          event_id: string | null;
          rule_id: string | null;
          channel: "email" | "slack" | "in_app";
          title: string;
          body: string;
          action_url: string | null;
          metadata: Json;
          status: "pending" | "sent" | "delivered" | "read" | "failed";
          error_message: string | null;
          sent_at: string | null;
          delivered_at: string | null;
          read_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          user_id: string;
          event_id?: string | null;
          rule_id?: string | null;
          channel: "email" | "slack" | "in_app";
          title: string;
          body: string;
          action_url?: string | null;
          metadata?: Json;
          status?: "pending" | "sent" | "delivered" | "read" | "failed";
          error_message?: string | null;
          sent_at?: string | null;
          delivered_at?: string | null;
          read_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          user_id?: string;
          event_id?: string | null;
          rule_id?: string | null;
          channel?: "email" | "slack" | "in_app";
          title?: string;
          body?: string;
          action_url?: string | null;
          metadata?: Json;
          status?: "pending" | "sent" | "delivered" | "read" | "failed";
          error_message?: string | null;
          sent_at?: string | null;
          delivered_at?: string | null;
          read_at?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "notifications_workspace_id_fkey";
            columns: ["workspace_id"];
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "notifications_user_id_fkey";
            columns: ["user_id"];
            referencedRelation: "users";
            referencedColumns: ["id"];
          }
        ];
      };
      notification_rules: {
        Row: {
          id: string;
          workspace_id: string;
          created_by: string | null;
          name: string;
          description: string | null;
          event_types: string[];
          conditions: Json;
          channels: string[];
          recipients: Json;
          template_override: Json | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          created_by?: string | null;
          name: string;
          description?: string | null;
          event_types: string[];
          conditions?: Json;
          channels: string[];
          recipients: Json;
          template_override?: Json | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          created_by?: string | null;
          name?: string;
          description?: string | null;
          event_types?: string[];
          conditions?: Json;
          channels?: string[];
          recipients?: Json;
          template_override?: Json | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "notification_rules_workspace_id_fkey";
            columns: ["workspace_id"];
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          }
        ];
      };
      notification_preferences: {
        Row: {
          id: string;
          user_id: string;
          workspace_id: string;
          email_enabled: boolean;
          slack_enabled: boolean;
          in_app_enabled: boolean;
          digest_frequency: "realtime" | "hourly" | "daily" | "weekly";
          digest_time: string;
          digest_timezone: string;
          quiet_hours_enabled: boolean;
          quiet_hours_start: string | null;
          quiet_hours_end: string | null;
          event_preferences: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          workspace_id: string;
          email_enabled?: boolean;
          slack_enabled?: boolean;
          in_app_enabled?: boolean;
          digest_frequency?: "realtime" | "hourly" | "daily" | "weekly";
          digest_time?: string;
          digest_timezone?: string;
          quiet_hours_enabled?: boolean;
          quiet_hours_start?: string | null;
          quiet_hours_end?: string | null;
          event_preferences?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          workspace_id?: string;
          email_enabled?: boolean;
          slack_enabled?: boolean;
          in_app_enabled?: boolean;
          digest_frequency?: "realtime" | "hourly" | "daily" | "weekly";
          digest_time?: string;
          digest_timezone?: string;
          quiet_hours_enabled?: boolean;
          quiet_hours_start?: string | null;
          quiet_hours_end?: string | null;
          event_preferences?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "notification_preferences_user_id_fkey";
            columns: ["user_id"];
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "notification_preferences_workspace_id_fkey";
            columns: ["workspace_id"];
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          }
        ];
      };
      quality_gates: {
        Row: {
          id: string;
          workspace_id: string;
          name: string;
          description: string | null;
          trigger_transition: string;
          min_score: number;
          action: "block" | "warn" | "comment";
          required_dimensions: string[] | null;
          notification_channels: string[];
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          name: string;
          description?: string | null;
          trigger_transition: string;
          min_score: number;
          action: "block" | "warn" | "comment";
          required_dimensions?: string[] | null;
          notification_channels?: string[];
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          name?: string;
          description?: string | null;
          trigger_transition?: string;
          min_score?: number;
          action?: "block" | "warn" | "comment";
          required_dimensions?: string[] | null;
          notification_channels?: string[];
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "quality_gates_workspace_id_fkey";
            columns: ["workspace_id"];
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          }
        ];
      };
      quality_violations: {
        Row: {
          id: string;
          workspace_id: string;
          story_id: string;
          gate_id: string;
          violation_type: "score_below_threshold" | "missing_dimension" | "blocked";
          score_at_time: number;
          required_score: number;
          jira_comment_id: string | null;
          resolution_status: "open" | "resolved" | "waived" | "expired";
          resolved_at: string | null;
          resolved_by: string | null;
          resolution_notes: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          story_id: string;
          gate_id: string;
          violation_type: "score_below_threshold" | "missing_dimension" | "blocked";
          score_at_time: number;
          required_score: number;
          jira_comment_id?: string | null;
          resolution_status?: "open" | "resolved" | "waived" | "expired";
          resolved_at?: string | null;
          resolved_by?: string | null;
          resolution_notes?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          story_id?: string;
          gate_id?: string;
          violation_type?: "score_below_threshold" | "missing_dimension" | "blocked";
          score_at_time?: number;
          required_score?: number;
          jira_comment_id?: string | null;
          resolution_status?: "open" | "resolved" | "waived" | "expired";
          resolved_at?: string | null;
          resolved_by?: string | null;
          resolution_notes?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "quality_violations_workspace_id_fkey";
            columns: ["workspace_id"];
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "quality_violations_story_id_fkey";
            columns: ["story_id"];
            referencedRelation: "stories";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "quality_violations_gate_id_fkey";
            columns: ["gate_id"];
            referencedRelation: "quality_gates";
            referencedColumns: ["id"];
          }
        ];
      };
      scenarios: {
        Row: {
          id: string;
          workspace_id: string;
          created_by: string;
          name: string;
          description: string | null;
          baseline: Json;
          changes: Json;
          results: Json | null;
          status: "draft" | "simulated" | "applied" | "archived";
          simulated_at: string | null;
          applied_at: string | null;
          applied_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          created_by: string;
          name: string;
          description?: string | null;
          baseline: Json;
          changes: Json;
          results?: Json | null;
          status?: "draft" | "simulated" | "applied" | "archived";
          simulated_at?: string | null;
          applied_at?: string | null;
          applied_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          created_by?: string;
          name?: string;
          description?: string | null;
          baseline?: Json;
          changes?: Json;
          results?: Json | null;
          status?: "draft" | "simulated" | "applied" | "archived";
          simulated_at?: string | null;
          applied_at?: string | null;
          applied_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "scenarios_workspace_id_fkey";
            columns: ["workspace_id"];
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "scenarios_created_by_fkey";
            columns: ["created_by"];
            referencedRelation: "users";
            referencedColumns: ["id"];
          }
        ];
      };
      team_member_profiles: {
        Row: {
          id: string;
          workspace_id: string;
          user_id: string;
          metrics: Json;
          strengths: string[] | null;
          growth_areas: string[] | null;
          coaching_suggestions: Json | null;
          velocity_trend: "improving" | "stable" | "declining" | null;
          quality_trend: "improving" | "stable" | "declining" | null;
          visibility: "self_only" | "manager_visible" | "team_visible" | "anonymous_team";
          last_calculated_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          user_id: string;
          metrics?: Json;
          strengths?: string[] | null;
          growth_areas?: string[] | null;
          coaching_suggestions?: Json | null;
          velocity_trend?: "improving" | "stable" | "declining" | null;
          quality_trend?: "improving" | "stable" | "declining" | null;
          visibility?: "self_only" | "manager_visible" | "team_visible" | "anonymous_team";
          last_calculated_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          user_id?: string;
          metrics?: Json;
          strengths?: string[] | null;
          growth_areas?: string[] | null;
          coaching_suggestions?: Json | null;
          velocity_trend?: "improving" | "stable" | "declining" | null;
          quality_trend?: "improving" | "stable" | "declining" | null;
          visibility?: "self_only" | "manager_visible" | "team_visible" | "anonymous_team";
          last_calculated_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "team_member_profiles_workspace_id_fkey";
            columns: ["workspace_id"];
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "team_member_profiles_user_id_fkey";
            columns: ["user_id"];
            referencedRelation: "users";
            referencedColumns: ["id"];
          }
        ];
      };
      team_member_metrics_history: {
        Row: {
          id: string;
          profile_id: string;
          period_start: string;
          period_end: string;
          metrics: Json;
          created_at: string;
        };
        Insert: {
          id?: string;
          profile_id: string;
          period_start: string;
          period_end: string;
          metrics: Json;
          created_at?: string;
        };
        Update: {
          id?: string;
          profile_id?: string;
          period_start?: string;
          period_end?: string;
          metrics?: Json;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "team_member_metrics_history_profile_id_fkey";
            columns: ["profile_id"];
            referencedRelation: "team_member_profiles";
            referencedColumns: ["id"];
          }
        ];
      };
      program_health_scores: {
        Row: {
          id: string;
          workspace_id: string;
          pi_id: string | null;
          health_score: number;
          health_status: "excellent" | "good" | "at_risk" | "critical";
          dimensions: Json;
          top_positive_drivers: Json | null;
          top_negative_drivers: Json | null;
          ai_recommendations: Json | null;
          calculated_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          pi_id?: string | null;
          health_score: number;
          health_status: "excellent" | "good" | "at_risk" | "critical";
          dimensions: Json;
          top_positive_drivers?: Json | null;
          top_negative_drivers?: Json | null;
          ai_recommendations?: Json | null;
          calculated_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          pi_id?: string | null;
          health_score?: number;
          health_status?: "excellent" | "good" | "at_risk" | "critical";
          dimensions?: Json;
          top_positive_drivers?: Json | null;
          top_negative_drivers?: Json | null;
          ai_recommendations?: Json | null;
          calculated_at?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "program_health_scores_workspace_id_fkey";
            columns: ["workspace_id"];
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "program_health_scores_pi_id_fkey";
            columns: ["pi_id"];
            referencedRelation: "program_increments";
            referencedColumns: ["id"];
          }
        ];
      };
      sprint_predictions: {
        Row: {
          id: string;
          workspace_id: string;
          sprint_id: number;
          risk_score: number;
          risk_level: "low" | "medium" | "high" | "critical";
          contributing_factors: Json;
          recommendations: Json | null;
          actual_completion_rate: number | null;
          actual_outcome: "on_track" | "partial" | "failed" | null;
          prediction_accuracy: number | null;
          predicted_at: string;
          evaluated_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          sprint_id: number;
          risk_score: number;
          risk_level: "low" | "medium" | "high" | "critical";
          contributing_factors: Json;
          recommendations?: Json | null;
          actual_completion_rate?: number | null;
          actual_outcome?: "on_track" | "partial" | "failed" | null;
          prediction_accuracy?: number | null;
          predicted_at?: string;
          evaluated_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          sprint_id?: number;
          risk_score?: number;
          risk_level?: "low" | "medium" | "high" | "critical";
          contributing_factors?: Json;
          recommendations?: Json | null;
          actual_completion_rate?: number | null;
          actual_outcome?: "on_track" | "partial" | "failed" | null;
          prediction_accuracy?: number | null;
          predicted_at?: string;
          evaluated_at?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "sprint_predictions_workspace_id_fkey";
            columns: ["workspace_id"];
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          }
        ];
      };
      story_predictions: {
        Row: {
          id: string;
          workspace_id: string;
          story_id: string;
          sprint_id: number | null;
          slip_probability: number;
          risk_factors: Json;
          recommended_actions: Json | null;
          actual_slipped: boolean | null;
          predicted_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          story_id: string;
          sprint_id?: number | null;
          slip_probability: number;
          risk_factors: Json;
          recommended_actions?: Json | null;
          actual_slipped?: boolean | null;
          predicted_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          story_id?: string;
          sprint_id?: number | null;
          slip_probability?: number;
          risk_factors?: Json;
          recommended_actions?: Json | null;
          actual_slipped?: boolean | null;
          predicted_at?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "story_predictions_workspace_id_fkey";
            columns: ["workspace_id"];
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "story_predictions_story_id_fkey";
            columns: ["story_id"];
            referencedRelation: "stories";
            referencedColumns: ["id"];
          }
        ];
      };
      program_increments: {
        Row: {
          id: string;
          workspace_id: string;
          name: string;
          start_date: string | null;
          end_date: string | null;
          status: "planning" | "active" | "completed";
          iterations: number;
          canvas_data: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          name: string;
          start_date?: string | null;
          end_date?: string | null;
          status?: "planning" | "active" | "completed";
          iterations?: number;
          canvas_data?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          name?: string;
          start_date?: string | null;
          end_date?: string | null;
          status?: "planning" | "active" | "completed";
          iterations?: number;
          canvas_data?: Json | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "program_increments_workspace_id_fkey";
            columns: ["workspace_id"];
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          }
        ];
      };
      pi_teams: {
        Row: {
          id: string;
          pi_id: string;
          name: string;
          jira_board_id: string | null;
          capacity_per_iteration: number[] | null;
          velocity_history: number[] | null;
        };
        Insert: {
          id?: string;
          pi_id: string;
          name: string;
          jira_board_id?: string | null;
          capacity_per_iteration?: number[] | null;
          velocity_history?: number[] | null;
        };
        Update: {
          id?: string;
          pi_id?: string;
          name?: string;
          jira_board_id?: string | null;
          capacity_per_iteration?: number[] | null;
          velocity_history?: number[] | null;
        };
        Relationships: [
          {
            foreignKeyName: "pi_teams_pi_id_fkey";
            columns: ["pi_id"];
            referencedRelation: "program_increments";
            referencedColumns: ["id"];
          }
        ];
      };
      pi_dependencies: {
        Row: {
          id: string;
          pi_id: string;
          from_story_id: string;
          to_story_id: string;
          from_team_id: string | null;
          to_team_id: string | null;
          status: "open" | "resolved" | "at_risk" | "blocked";
          created_at: string;
        };
        Insert: {
          id?: string;
          pi_id: string;
          from_story_id: string;
          to_story_id: string;
          from_team_id?: string | null;
          to_team_id?: string | null;
          status?: "open" | "resolved" | "at_risk" | "blocked";
          created_at?: string;
        };
        Update: {
          id?: string;
          pi_id?: string;
          from_story_id?: string;
          to_story_id?: string;
          from_team_id?: string | null;
          to_team_id?: string | null;
          status?: "open" | "resolved" | "at_risk" | "blocked";
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "pi_dependencies_pi_id_fkey";
            columns: ["pi_id"];
            referencedRelation: "program_increments";
            referencedColumns: ["id"];
          }
        ];
      };
      subscriptions: {
        Row: {
          id: string;
          workspace_id: string;
          paystack_customer_code: string;
          paystack_subscription_code: string | null;
          plan: "free" | "pro" | "team" | "enterprise";
          status: "active" | "cancelled" | "past_due";
          current_period_start: string;
          current_period_end: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          paystack_customer_code: string;
          paystack_subscription_code?: string | null;
          plan?: "free" | "pro" | "team" | "enterprise";
          status?: "active" | "cancelled" | "past_due";
          current_period_start: string;
          current_period_end: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          paystack_customer_code?: string;
          paystack_subscription_code?: string | null;
          plan?: "free" | "pro" | "team" | "enterprise";
          status?: "active" | "cancelled" | "past_due";
          current_period_start?: string;
          current_period_end?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "subscriptions_workspace_id_fkey";
            columns: ["workspace_id"];
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          }
        ];
      };
      team_invitations: {
        Row: {
          id: string;
          workspace_id: string;
          email: string;
          role: "admin" | "member" | "viewer";
          invited_by: string;
          token: string;
          expires_at: string;
          accepted_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          email: string;
          role?: "admin" | "member" | "viewer";
          invited_by: string;
          token?: string;
          expires_at?: string;
          accepted_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          email?: string;
          role?: "admin" | "member" | "viewer";
          invited_by?: string;
          token?: string;
          expires_at?: string;
          accepted_at?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "team_invitations_workspace_id_fkey";
            columns: ["workspace_id"];
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          }
        ];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

// Helper types for easier usage
export type Tables<
  PublicTableNameOrOptions extends
    | keyof (Database["public"]["Tables"] & Database["public"]["Views"])
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof (Database[PublicTableNameOrOptions["schema"]]["Tables"] &
        Database[PublicTableNameOrOptions["schema"]]["Views"])
    : never = never
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? (Database[PublicTableNameOrOptions["schema"]]["Tables"] &
      Database[PublicTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : PublicTableNameOrOptions extends keyof (Database["public"]["Tables"] &
      Database["public"]["Views"])
  ? (Database["public"]["Tables"] &
      Database["public"]["Views"])[PublicTableNameOrOptions] extends {
      Row: infer R;
    }
    ? R
    : never
  : never;

export type TablesInsert<
  PublicTableNameOrOptions extends
    | keyof Database["public"]["Tables"]
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof Database[PublicTableNameOrOptions["schema"]]["Tables"]
    : never = never
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? Database[PublicTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : PublicTableNameOrOptions extends keyof Database["public"]["Tables"]
  ? Database["public"]["Tables"][PublicTableNameOrOptions] extends {
      Insert: infer I;
    }
    ? I
    : never
  : never;

export type TablesUpdate<
  PublicTableNameOrOptions extends
    | keyof Database["public"]["Tables"]
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof Database[PublicTableNameOrOptions["schema"]]["Tables"]
    : never = never
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? Database[PublicTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : PublicTableNameOrOptions extends keyof Database["public"]["Tables"]
  ? Database["public"]["Tables"][PublicTableNameOrOptions] extends {
      Update: infer U;
    }
    ? U
    : never
  : never;

// Convenience type aliases
export type Workspace = Tables<"workspaces">;
export type User = Tables<"users">;
export type WorkspaceMember = Tables<"workspace_members">;
export type JiraConnection = Tables<"jira_connections">;
export type Story = Tables<"stories">;
export type Rubric = Tables<"rubrics">;
export type StoryScore = Tables<"story_scores">;
export type SignalUpdate = Tables<"signal_updates">;
export type Decision = Tables<"decisions">;
export type ProgramIncrement = Tables<"program_increments">;
export type PITeam = Tables<"pi_teams">;
export type PIDependency = Tables<"pi_dependencies">;
export type Subscription = Tables<"subscriptions">;
export type TeamInvitation = Tables<"team_invitations">;

// New Decision Intelligence types
export type DecisionStoryLink = Tables<"decision_story_links">;
export type DecisionTemplate = Tables<"decision_templates">;
export type JiraSyncOperation = Tables<"jira_sync_operations">;
export type NotificationEvent = Tables<"notification_events">;
export type Notification = Tables<"notifications">;
export type NotificationRule = Tables<"notification_rules">;
export type NotificationPreference = Tables<"notification_preferences">;
export type QualityGate = Tables<"quality_gates">;
export type QualityViolation = Tables<"quality_violations">;
export type Scenario = Tables<"scenarios">;
export type TeamMemberProfile = Tables<"team_member_profiles">;
export type TeamMemberMetricsHistory = Tables<"team_member_metrics_history">;
export type ProgramHealthScore = Tables<"program_health_scores">;
export type SprintPrediction = Tables<"sprint_predictions">;
export type StoryPrediction = Tables<"story_predictions">;

// Insert types
export type WorkspaceInsert = TablesInsert<"workspaces">;
export type UserInsert = TablesInsert<"users">;
export type StoryInsert = TablesInsert<"stories">;
export type SignalUpdateInsert = TablesInsert<"signal_updates">;
export type ProgramIncrementInsert = TablesInsert<"program_increments">;
export type TeamInvitationInsert = TablesInsert<"team_invitations">;
export type DecisionInsert = TablesInsert<"decisions">;
export type ScenarioInsert = TablesInsert<"scenarios">;
export type QualityGateInsert = TablesInsert<"quality_gates">;
