/**
 * Supabase Database Types for FORGE
 *
 * This file will be auto-generated by running:
 * supabase gen types typescript --project-id YOUR_PROJECT_REF > types/supabase.ts
 *
 * For now, this contains the initial schema types matching our migration files.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      workspace_members: {
        Row: {
          id: string;
          workspace_id: string;
          user_id: string;
          role: "owner" | "admin" | "member" | "viewer";
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          user_id: string;
          role: "owner" | "admin" | "member" | "viewer";
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          user_id?: string;
          role?: "owner" | "admin" | "member" | "viewer";
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "workspace_members_workspace_id_fkey";
            columns: ["workspace_id"];
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "workspace_members_user_id_fkey";
            columns: ["user_id"];
            referencedRelation: "users";
            referencedColumns: ["id"];
          }
        ];
      };
      workspaces: {
        Row: {
          id: string;
          name: string;
          slug: string;
          team_size: string | null;
          plan: "free" | "pro" | "team" | "enterprise";
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug?: string;
          team_size?: string | null;
          plan?: "free" | "pro" | "team" | "enterprise";
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          team_size?: string | null;
          plan?: "free" | "pro" | "team" | "enterprise";
          created_by?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      users: {
        Row: {
          id: string;
          workspace_id: string | null;
          email: string;
          full_name: string | null;
          display_name: string | null;
          role: string | null;
          avatar_url: string | null;
          onboarding_completed: boolean;
          created_at: string;
          updated_at: string | null;
        };
        Insert: {
          id: string;
          workspace_id?: string | null;
          email: string;
          full_name?: string | null;
          display_name?: string | null;
          role?: string | null;
          avatar_url?: string | null;
          onboarding_completed?: boolean;
          created_at?: string;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          workspace_id?: string | null;
          email?: string;
          full_name?: string | null;
          display_name?: string | null;
          role?: string | null;
          avatar_url?: string | null;
          onboarding_completed?: boolean;
          created_at?: string;
          updated_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "users_workspace_id_fkey";
            columns: ["workspace_id"];
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          }
        ];
      };
      jira_connections: {
        Row: {
          id: string;
          workspace_id: string;
          site_url: string;
          access_token: string;
          refresh_token: string | null;
          token_expires: string | null;
          last_synced_at: string | null;
          sync_status: "idle" | "syncing" | "error";
        };
        Insert: {
          id?: string;
          workspace_id: string;
          site_url: string;
          access_token: string;
          refresh_token?: string | null;
          token_expires?: string | null;
          last_synced_at?: string | null;
          sync_status?: "idle" | "syncing" | "error";
        };
        Update: {
          id?: string;
          workspace_id?: string;
          site_url?: string;
          access_token?: string;
          refresh_token?: string | null;
          token_expires?: string | null;
          last_synced_at?: string | null;
          sync_status?: "idle" | "syncing" | "error";
        };
        Relationships: [
          {
            foreignKeyName: "jira_connections_workspace_id_fkey";
            columns: ["workspace_id"];
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          }
        ];
      };
      stories: {
        Row: {
          id: string;
          workspace_id: string;
          jira_id: string;
          jira_key: string;
          title: string;
          description: string | null;
          acceptance_criteria: string | null;
          story_points: number | null;
          status: string | null;
          assignee_id: string | null;
          epic_key: string | null;
          sprint_id: string | null;
          labels: string[] | null;
          jira_updated_at: string | null;
          synced_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          jira_id: string;
          jira_key: string;
          title: string;
          description?: string | null;
          acceptance_criteria?: string | null;
          story_points?: number | null;
          status?: string | null;
          assignee_id?: string | null;
          epic_key?: string | null;
          sprint_id?: string | null;
          labels?: string[] | null;
          jira_updated_at?: string | null;
          synced_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          jira_id?: string;
          jira_key?: string;
          title?: string;
          description?: string | null;
          acceptance_criteria?: string | null;
          story_points?: number | null;
          status?: string | null;
          assignee_id?: string | null;
          epic_key?: string | null;
          sprint_id?: string | null;
          labels?: string[] | null;
          jira_updated_at?: string | null;
          synced_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "stories_workspace_id_fkey";
            columns: ["workspace_id"];
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          }
        ];
      };
      rubrics: {
        Row: {
          id: string;
          workspace_id: string;
          name: string;
          is_default: boolean;
          weights: Json;
          blocklist: string[] | null;
          threshold: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          name: string;
          is_default?: boolean;
          weights: Json;
          blocklist?: string[] | null;
          threshold?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          name?: string;
          is_default?: boolean;
          weights?: Json;
          blocklist?: string[] | null;
          threshold?: number;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "rubrics_workspace_id_fkey";
            columns: ["workspace_id"];
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          }
        ];
      };
      story_scores: {
        Row: {
          id: string;
          story_id: string;
          rubric_id: string;
          total_score: number;
          completeness: number | null;
          clarity: number | null;
          estimability: number | null;
          traceability: number | null;
          testability: number | null;
          ai_suggestions: Json | null;
          scored_at: string;
        };
        Insert: {
          id?: string;
          story_id: string;
          rubric_id: string;
          total_score: number;
          completeness?: number | null;
          clarity?: number | null;
          estimability?: number | null;
          traceability?: number | null;
          testability?: number | null;
          ai_suggestions?: Json | null;
          scored_at?: string;
        };
        Update: {
          id?: string;
          story_id?: string;
          rubric_id?: string;
          total_score?: number;
          completeness?: number | null;
          clarity?: number | null;
          estimability?: number | null;
          traceability?: number | null;
          testability?: number | null;
          ai_suggestions?: Json | null;
          scored_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "story_scores_story_id_fkey";
            columns: ["story_id"];
            referencedRelation: "stories";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "story_scores_rubric_id_fkey";
            columns: ["rubric_id"];
            referencedRelation: "rubrics";
            referencedColumns: ["id"];
          }
        ];
      };
      signal_updates: {
        Row: {
          id: string;
          workspace_id: string;
          author_id: string;
          title: string | null;
          sprint_ref: string | null;
          context_data: Json | null;
          audiences: string[] | null;
          drafts: Json | null;
          status: "draft" | "sent" | "archived";
          sent_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          author_id: string;
          title?: string | null;
          sprint_ref?: string | null;
          context_data?: Json | null;
          audiences?: string[] | null;
          drafts?: Json | null;
          status?: "draft" | "sent" | "archived";
          sent_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          author_id?: string;
          title?: string | null;
          sprint_ref?: string | null;
          context_data?: Json | null;
          audiences?: string[] | null;
          drafts?: Json | null;
          status?: "draft" | "sent" | "archived";
          sent_at?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "signal_updates_workspace_id_fkey";
            columns: ["workspace_id"];
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "signal_updates_author_id_fkey";
            columns: ["author_id"];
            referencedRelation: "users";
            referencedColumns: ["id"];
          }
        ];
      };
      decisions: {
        Row: {
          id: string;
          workspace_id: string;
          signal_update_id: string | null;
          made_by_id: string;
          title: string;
          reasoning: string | null;
          affected_tickets: string[] | null;
          tags: string[] | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          signal_update_id?: string | null;
          made_by_id: string;
          title: string;
          reasoning?: string | null;
          affected_tickets?: string[] | null;
          tags?: string[] | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          signal_update_id?: string | null;
          made_by_id?: string;
          title?: string;
          reasoning?: string | null;
          affected_tickets?: string[] | null;
          tags?: string[] | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "decisions_workspace_id_fkey";
            columns: ["workspace_id"];
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "decisions_signal_update_id_fkey";
            columns: ["signal_update_id"];
            referencedRelation: "signal_updates";
            referencedColumns: ["id"];
          }
        ];
      };
      program_increments: {
        Row: {
          id: string;
          workspace_id: string;
          name: string;
          start_date: string | null;
          end_date: string | null;
          status: "planning" | "active" | "completed";
          iterations: number;
          canvas_data: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          name: string;
          start_date?: string | null;
          end_date?: string | null;
          status?: "planning" | "active" | "completed";
          iterations?: number;
          canvas_data?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          name?: string;
          start_date?: string | null;
          end_date?: string | null;
          status?: "planning" | "active" | "completed";
          iterations?: number;
          canvas_data?: Json | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "program_increments_workspace_id_fkey";
            columns: ["workspace_id"];
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          }
        ];
      };
      pi_teams: {
        Row: {
          id: string;
          pi_id: string;
          name: string;
          jira_board_id: string | null;
          capacity_per_iteration: number[] | null;
          velocity_history: number[] | null;
        };
        Insert: {
          id?: string;
          pi_id: string;
          name: string;
          jira_board_id?: string | null;
          capacity_per_iteration?: number[] | null;
          velocity_history?: number[] | null;
        };
        Update: {
          id?: string;
          pi_id?: string;
          name?: string;
          jira_board_id?: string | null;
          capacity_per_iteration?: number[] | null;
          velocity_history?: number[] | null;
        };
        Relationships: [
          {
            foreignKeyName: "pi_teams_pi_id_fkey";
            columns: ["pi_id"];
            referencedRelation: "program_increments";
            referencedColumns: ["id"];
          }
        ];
      };
      pi_dependencies: {
        Row: {
          id: string;
          pi_id: string;
          from_story_id: string;
          to_story_id: string;
          from_team_id: string | null;
          to_team_id: string | null;
          status: "open" | "resolved" | "at_risk" | "blocked";
          created_at: string;
        };
        Insert: {
          id?: string;
          pi_id: string;
          from_story_id: string;
          to_story_id: string;
          from_team_id?: string | null;
          to_team_id?: string | null;
          status?: "open" | "resolved" | "at_risk" | "blocked";
          created_at?: string;
        };
        Update: {
          id?: string;
          pi_id?: string;
          from_story_id?: string;
          to_story_id?: string;
          from_team_id?: string | null;
          to_team_id?: string | null;
          status?: "open" | "resolved" | "at_risk" | "blocked";
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "pi_dependencies_pi_id_fkey";
            columns: ["pi_id"];
            referencedRelation: "program_increments";
            referencedColumns: ["id"];
          }
        ];
      };
      subscriptions: {
        Row: {
          id: string;
          workspace_id: string;
          paystack_customer_code: string;
          paystack_subscription_code: string | null;
          plan: "free" | "pro" | "team" | "enterprise";
          status: "active" | "cancelled" | "past_due";
          current_period_start: string;
          current_period_end: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          paystack_customer_code: string;
          paystack_subscription_code?: string | null;
          plan?: "free" | "pro" | "team" | "enterprise";
          status?: "active" | "cancelled" | "past_due";
          current_period_start: string;
          current_period_end: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          paystack_customer_code?: string;
          paystack_subscription_code?: string | null;
          plan?: "free" | "pro" | "team" | "enterprise";
          status?: "active" | "cancelled" | "past_due";
          current_period_start?: string;
          current_period_end?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "subscriptions_workspace_id_fkey";
            columns: ["workspace_id"];
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          }
        ];
      };
      team_invitations: {
        Row: {
          id: string;
          workspace_id: string;
          email: string;
          role: "admin" | "member" | "viewer";
          invited_by: string;
          token: string;
          expires_at: string;
          accepted_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          workspace_id: string;
          email: string;
          role?: "admin" | "member" | "viewer";
          invited_by: string;
          token?: string;
          expires_at?: string;
          accepted_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          workspace_id?: string;
          email?: string;
          role?: "admin" | "member" | "viewer";
          invited_by?: string;
          token?: string;
          expires_at?: string;
          accepted_at?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "team_invitations_workspace_id_fkey";
            columns: ["workspace_id"];
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          }
        ];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

// Helper types for easier usage
export type Tables<
  PublicTableNameOrOptions extends
    | keyof (Database["public"]["Tables"] & Database["public"]["Views"])
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof (Database[PublicTableNameOrOptions["schema"]]["Tables"] &
        Database[PublicTableNameOrOptions["schema"]]["Views"])
    : never = never
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? (Database[PublicTableNameOrOptions["schema"]]["Tables"] &
      Database[PublicTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : PublicTableNameOrOptions extends keyof (Database["public"]["Tables"] &
      Database["public"]["Views"])
  ? (Database["public"]["Tables"] &
      Database["public"]["Views"])[PublicTableNameOrOptions] extends {
      Row: infer R;
    }
    ? R
    : never
  : never;

export type TablesInsert<
  PublicTableNameOrOptions extends
    | keyof Database["public"]["Tables"]
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof Database[PublicTableNameOrOptions["schema"]]["Tables"]
    : never = never
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? Database[PublicTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : PublicTableNameOrOptions extends keyof Database["public"]["Tables"]
  ? Database["public"]["Tables"][PublicTableNameOrOptions] extends {
      Insert: infer I;
    }
    ? I
    : never
  : never;

export type TablesUpdate<
  PublicTableNameOrOptions extends
    | keyof Database["public"]["Tables"]
    | { schema: keyof Database },
  TableName extends PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof Database[PublicTableNameOrOptions["schema"]]["Tables"]
    : never = never
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? Database[PublicTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : PublicTableNameOrOptions extends keyof Database["public"]["Tables"]
  ? Database["public"]["Tables"][PublicTableNameOrOptions] extends {
      Update: infer U;
    }
    ? U
    : never
  : never;

// Convenience type aliases
export type Workspace = Tables<"workspaces">;
export type User = Tables<"users">;
export type WorkspaceMember = Tables<"workspace_members">;
export type JiraConnection = Tables<"jira_connections">;
export type Story = Tables<"stories">;
export type Rubric = Tables<"rubrics">;
export type StoryScore = Tables<"story_scores">;
export type SignalUpdate = Tables<"signal_updates">;
export type Decision = Tables<"decisions">;
export type ProgramIncrement = Tables<"program_increments">;
export type PITeam = Tables<"pi_teams">;
export type PIDependency = Tables<"pi_dependencies">;
export type Subscription = Tables<"subscriptions">;
export type TeamInvitation = Tables<"team_invitations">;

// Insert types
export type WorkspaceInsert = TablesInsert<"workspaces">;
export type UserInsert = TablesInsert<"users">;
export type StoryInsert = TablesInsert<"stories">;
export type SignalUpdateInsert = TablesInsert<"signal_updates">;
export type ProgramIncrementInsert = TablesInsert<"program_increments">;
export type TeamInvitationInsert = TablesInsert<"team_invitations">;
