"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import Link from "next/link";
import {
  ArrowLeft,
  Sparkles,
  Send,
  Save,
  Users,
  Briefcase,
  Building2,
  Crown,
  Loader2,
} from "lucide-react";
import { PageHeader } from "@/components/layout/page-header";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Textarea, Label } from "@/components/ui/input";
import { useToastActions } from "@/components/ui/toast";
import { cn } from "@/lib/utils";
import {
  Select,
  SelectTrigger,
  SelectValue,
  SelectContent,
  SelectItem,
} from "@/components/ui/select";
import { DEMO_SPRINTS, DEMO_STORIES, calculateSprintHealth, getScoreDistribution } from "@/lib/demo/mock-data";
import type { AudienceType } from "@/types/signal";

const AUDIENCES: { id: AudienceType; label: string; icon: React.ElementType; description: string }[] = [
  { id: "executive", label: "Executive Team", icon: Crown, description: "C-suite and leadership" },
  { id: "team", label: "Dev Team", icon: Users, description: "Engineers and designers" },
  { id: "client", label: "Client/Customer", icon: Briefcase, description: "External stakeholders" },
  { id: "board", label: "Board/Investors", icon: Building2, description: "Board members and investors" },
];

const GENERATED_CONTENT = `## Sprint 22 Progress Update

**Overall Status:** On Track

### Highlights
- OAuth2 authentication implementation is progressing well, currently at 80% completion
- JIRA integration has been deployed and is syncing successfully every 15 minutes
- Story quality has improved significantly this sprint with an average score of 69

### Key Metrics
| Metric | Value |
|--------|-------|
| Stories Completed | 2 of 12 |
| Story Points | 9 of 48 |
| Average Quality Score | 69 |
| Stories at Risk | 5 |

### Stories at Risk
The following stories need attention due to low quality scores:
1. **FORGE-102** - Payment gateway integration (Score: 38) - Missing acceptance criteria
2. **FORGE-109** - Export functionality (Score: 35) - Vague description
3. **FORGE-111** - Team invitation flow (Score: 42) - Incomplete requirements

### Blockers
- No critical blockers at this time
- Minor: Awaiting design assets for notification templates

### Next Steps
1. Complete OAuth flow implementation by mid-sprint
2. Address story quality issues for at-risk items
3. Begin payment integration testing
4. Prepare for stakeholder demo on Friday

---
*Generated by FORGE AI based on Sprint 22 data*`;

export default function DemoNewSignalPage() {
  const toast = useToastActions();
  const [selectedSprint, setSelectedSprint] = useState(DEMO_SPRINTS[0].id);
  const [selectedAudiences, setSelectedAudiences] = useState<AudienceType[]>([]);
  const [content, setContent] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [additionalContext, setAdditionalContext] = useState("");

  const toggleAudience = (audienceId: AudienceType) => {
    setSelectedAudiences((prev) =>
      prev.includes(audienceId)
        ? prev.filter((id) => id !== audienceId)
        : [...prev, audienceId]
    );
  };

  const handleGenerate = async () => {
    if (selectedAudiences.length === 0) {
      toast.error("Select audience", "Please select at least one audience");
      return;
    }

    setIsGenerating(true);

    // Simulate AI generation with streaming effect
    setContent("");
    const words = GENERATED_CONTENT.split(" ");

    for (let i = 0; i < words.length; i++) {
      await new Promise((resolve) => setTimeout(resolve, 20));
      setContent((prev) => prev + (i === 0 ? "" : " ") + words[i]);
    }

    setIsGenerating(false);
    toast.success("Draft generated", "AI has created your update draft");
  };

  const handleSaveDraft = () => {
    toast.success("Draft saved", "Your update has been saved as a draft");
  };

  const handleSend = () => {
    if (!content) {
      toast.error("No content", "Please generate or write content first");
      return;
    }
    toast.success("Update sent", `Sent to ${selectedAudiences.length} audience(s)`);
  };

  const sprintHealth = calculateSprintHealth(DEMO_STORIES);
  const distribution = getScoreDistribution(DEMO_STORIES);

  return (
    <div>
      <PageHeader
        title={
          <div className="flex items-center gap-3">
            <Link href="/demo/signal">
              <Button variant="ghost" size="sm">
                <ArrowLeft className="w-4 h-4" />
              </Button>
            </Link>
            <span className="text-text-primary">Create Update</span>
          </div>
        }
        actions={
          <div className="flex items-center gap-2">
            <Button variant="secondary" size="sm" onClick={handleSaveDraft} leftIcon={<Save className="w-4 h-4" />}>
              Save Draft
            </Button>
            <Button size="sm" onClick={handleSend} leftIcon={<Send className="w-4 h-4" />}>
              Send Update
            </Button>
          </div>
        }
      />

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left: Composer */}
        <div className="lg:col-span-2 space-y-6">
          {/* Context Selection */}
          <div className="bg-surface-01 border border-border rounded-lg p-5">
            <h3 className="text-sm font-medium text-text-primary mb-4">Update Context</h3>

            <div className="grid grid-cols-2 gap-4 mb-4">
              <div>
                <Label>Sprint</Label>
                <Select value={selectedSprint} onValueChange={setSelectedSprint}>
                  <SelectTrigger>
                    <SelectValue placeholder="Select sprint" />
                  </SelectTrigger>
                  <SelectContent>
                    {DEMO_SPRINTS.map((sprint) => (
                      <SelectItem key={sprint.id} value={sprint.id}>
                        {sprint.name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              <div>
                <Label>Audience</Label>
                <div className="flex flex-wrap gap-2 mt-2">
                  {selectedAudiences.length === 0 ? (
                    <span className="text-sm text-text-tertiary">Select below</span>
                  ) : (
                    selectedAudiences.map((aud) => (
                      <Badge key={aud} variant="good" size="sm">
                        {AUDIENCES.find((a) => a.id === aud)?.label}
                      </Badge>
                    ))
                  )}
                </div>
              </div>
            </div>

            {/* Audience Selection */}
            <div>
              <Label className="mb-2 block">Select Audiences</Label>
              <div className="grid grid-cols-2 gap-2">
                {AUDIENCES.map((audience) => {
                  const Icon = audience.icon;
                  const isSelected = selectedAudiences.includes(audience.id);
                  return (
                    <button
                      key={audience.id}
                      onClick={() => toggleAudience(audience.id)}
                      className={cn(
                        "flex items-center gap-3 p-3 rounded-lg border text-left transition-colors",
                        isSelected
                          ? "bg-iris-dim border-iris"
                          : "bg-surface-02 border-border hover:border-border-strong"
                      )}
                    >
                      <Icon className={cn("w-5 h-5", isSelected ? "text-iris" : "text-text-tertiary")} />
                      <div>
                        <div className={cn("text-sm font-medium", isSelected ? "text-iris" : "text-text-primary")}>
                          {audience.label}
                        </div>
                        <div className="text-xs text-text-tertiary">{audience.description}</div>
                      </div>
                    </button>
                  );
                })}
              </div>
            </div>

            {/* Additional Context */}
            <div className="mt-4">
              <Label>Additional Context (optional)</Label>
              <Textarea
                placeholder="Add any specific points you want highlighted..."
                value={additionalContext}
                onChange={(e) => setAdditionalContext(e.target.value)}
                rows={2}
              />
            </div>

            {/* Generate Button */}
            <div className="mt-4">
              <Button
                onClick={handleGenerate}
                disabled={isGenerating || selectedAudiences.length === 0}
                isLoading={isGenerating}
                leftIcon={<Sparkles className="w-4 h-4" />}
                className="w-full"
              >
                {isGenerating ? "Generating..." : "Generate with AI"}
              </Button>
            </div>
          </div>

          {/* Content Editor */}
          <div className="bg-surface-01 border border-border rounded-lg p-5">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-sm font-medium text-text-primary">Update Content</h3>
              {isGenerating && (
                <div className="flex items-center gap-2 text-xs text-iris">
                  <Loader2 className="w-3 h-3 animate-spin" />
                  AI is writing...
                </div>
              )}
            </div>
            <Textarea
              placeholder="Your update content will appear here after generation, or you can write your own..."
              value={content}
              onChange={(e) => setContent(e.target.value)}
              rows={20}
              className="font-mono text-sm"
            />
          </div>
        </div>

        {/* Right: Sprint Context */}
        <div className="space-y-6">
          {/* Sprint Summary */}
          <div className="bg-surface-01 border border-border rounded-lg p-5">
            <h3 className="text-sm font-medium text-text-secondary mb-4">Sprint Context</h3>
            <div className="space-y-4">
              <div>
                <div className="text-xs text-text-tertiary">Health Score</div>
                <div className="text-2xl font-bold text-text-primary">{sprintHealth}</div>
              </div>
              <div>
                <div className="text-xs text-text-tertiary">Stories</div>
                <div className="text-lg font-medium text-text-primary">{DEMO_STORIES.length}</div>
              </div>
              <div>
                <div className="text-xs text-text-tertiary mb-2">Score Distribution</div>
                <div className="flex gap-1">
                  <div className="flex-1 text-center">
                    <div className="text-jade font-bold">{distribution.excellent}</div>
                    <div className="text-xs text-text-tertiary">85+</div>
                  </div>
                  <div className="flex-1 text-center">
                    <div className="text-iris font-bold">{distribution.good}</div>
                    <div className="text-xs text-text-tertiary">70-84</div>
                  </div>
                  <div className="flex-1 text-center">
                    <div className="text-amber font-bold">{distribution.fair}</div>
                    <div className="text-xs text-text-tertiary">50-69</div>
                  </div>
                  <div className="flex-1 text-center">
                    <div className="text-coral font-bold">{distribution.poor}</div>
                    <div className="text-xs text-text-tertiary">&lt;50</div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Tips */}
          <div className="bg-iris-dim border border-iris/20 rounded-lg p-5">
            <h3 className="text-sm font-medium text-iris mb-3">AI Generation Tips</h3>
            <ul className="text-xs text-text-secondary space-y-2">
              <li>Select multiple audiences to generate tailored versions</li>
              <li>Add context to highlight specific achievements or concerns</li>
              <li>The AI uses real sprint data to generate accurate updates</li>
              <li>You can edit the generated content before sending</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
}
