-- Create program_increments table (PI Planning)
CREATE TABLE IF NOT EXISTS program_increments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  name TEXT NOT NULL, -- e.g., "PI 7 — Q2 2026"
  description TEXT,
  -- Timeline
  start_date DATE,
  end_date DATE,
  -- Configuration
  iterations INTEGER DEFAULT 5,
  iteration_length_weeks INTEGER DEFAULT 2,
  ip_iteration BOOLEAN DEFAULT TRUE, -- Innovation and Planning iteration
  -- Status
  status TEXT DEFAULT 'planning' CHECK (status IN ('planning', 'active', 'completed')),
  -- Canvas state (denormalized for performance)
  canvas_data JSONB,
  -- PI Objectives (generated by AI)
  objectives JSONB,
  -- Health metrics (updated during execution)
  health_data JSONB,
  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_program_increments_workspace ON program_increments(workspace_id);
CREATE INDEX IF NOT EXISTS idx_program_increments_status ON program_increments(status);
CREATE INDEX IF NOT EXISTS idx_program_increments_dates ON program_increments(start_date, end_date);

-- Enable RLS
ALTER TABLE program_increments ENABLE ROW LEVEL SECURITY;
